import persian number code to number formatted
bbc/news-vj-number-formatter pull request #9
Opened 2019-07-23 10:31 UTC by joshrayman

![Screen Shot 2019-07-23 at 11 24 37](https://user-images.githubusercontent.com/20838297/61705255-5ad48c00-ad3d-11e9-8a73-78ee3a051c1d.png)
(percentages)

Outstanding:
negative numbers
![Screen Shot 2019-07-23 at 11 25 55](https://user-images.githubusercontent.com/20838297/61705273-632cc700-ad3d-11e9-9a05-f0a8b3f65f0f.png)

2019-07-23 10:52 UTC, rushlet approved these changes
looks a bit weird, but if it has to be like that to work then 🤷‍♀

2019-07-23 18:53 UTC, rushlet requested changes

2019-07-23 18:53 UTC, rushlet commented on numberFormatter.js
> +        }
missed a comma here!

2019-07-25 12:59 UTC, rushlet requested changes

2019-07-25 12:59 UTC, rushlet commented on numberFormatter.js
> +            const numStr = num.toString();
is `num` supposed to be `number` ?

2019-07-25 13:00 UTC, joshrayman commented on numberFormatter.js
> +            const numStr = num.toString();
yes sorry

2019-08-07 15:52 UTC, merged